[package]
name = "wallpaper-switcher"
description = "Hyprland wallpaper-switcher"
license = "MIT"
version = "1.0.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
